#!/usr/bin/env bash
# steps/10-render-report.sh — Final report rendering
# Source this file; do not execute directly.

# shellcheck disable=SC2034,SC2154  # Cross-file globals (sourced context)

step_render_report() {
	log_header "10/11" "Rendu final du rapport"

	# ─── Footer with actionable recommendations ────────────────
	report_actions_footer "$TEP_MAX_SCORE"

	# ─── TEP signature ──────────────────────────────────────────
	report_separator
	report_text ""
	report_text "---"
	report_text ""
	report_text "*Generated by [TEP — Token Economy Paradigm](https://github.com/marc-music/tep)*"
	report_text "*Score: ${TEP_SCORE}/${TEP_MAX_SCORE} — ${TEP_TIMESTAMP}*"

	# ─── Atomic write to RESULT.md ──────────────────────────────
	report_finalize "$TEP_RESULT_FILE"

	# ─── Terminal summary ───────────────────────────────────────
	log_separator
	log_banner

	local result_size
	result_size=$(count_lines "$TEP_RESULT_FILE")

	log_summary "Score" "${TEP_SCORE}/${TEP_MAX_SCORE}"
	log_summary "Report" "$TEP_RESULT_FILE ($result_size lines)"

	if [[ $TEP_SCORE -eq $TEP_MAX_SCORE ]]; then
		log_ok "🎉 Configuration optimale — bravo !"
	elif [[ $TEP_SCORE -ge 6 ]]; then
		log_info "Bonne base. Lis RESULT.md pour les ajustements."
	else
		log_warn "Score faible. Lis RESULT.md et applique les recommandations."
	fi

	log_separator
	return 0
}